### ISSUE TITLE
TS node not found

### ISSUE THREAD

**Issue by trentjw** [zwave-js/zwave-js-server#100]
since my last issue was closed I am still have the same issue
pi@debianbase:~$ ts-node src/bin/server.ts /dev/tty0
-bash: ts-node: command not found
pi@debianbase:~$ npm install -g ts-node
-bash: npm: command not found
pi@debianbase:~$ npx ts-node
-bash: npx: command not found
pi@debianbase:~$

**Comment by trentjw** [comment]
Closing the issue does not solve the problem how about actual help?

**Comment by frenck** [comment]
Did you install node? npm?

**Comment by trentjw** [comment]
Tried to but got the results in above

**Comment by frenck** [comment]
> npm: command not found

But the command isn't found? Please make sure you install node & npm correct, for information about installing those, please check the nodejs website.

**Comment by trentjw** [comment]
> > npm: command not found
> 
> But the command isn't found? Please make sure you install node & npm correct, for information about installing those, please check the nodejs website.

I tried to install it and still get the command not found

**Comment by frenck** [comment]
I get that, I tried to say: That is kinda out of scope for this project.
Just like we can't help you install an operating system itself. You are more likely to get the right help within the resources/community of NodeJS & NPM.

**Comment by trentjw** [comment]
> I get that, I tried to say: That is kinda out of scope for this project.
> Just like we can't help you install an operating system itself. You are more likely to get the right help within the resources/community of NodeJS & NPM.

I have the OS installed with python 3.9 installed even manage to get I think the ZWavejs installed and even got this message Reading state information... Done
nodejs is already the newest version (10.23.1~dfsg-1~deb10u1).

**Comment by trentjw** [comment]
well since the stuff I do is out of the scope of this project, I finally without any help as per usual finally got it to the next step and as per usual I will make a step by step on making a Zwave-js server for the next poor idiot that is trying to migrate to the new standard that uses Venv a path that at least kind of works
