### ISSUE TITLE
Error: Cannot find module '/home/pi/src/bin/server.ts'

### ISSUE THREAD

**Issue by trentjw** [zwave-js/zwave-js-server#102]
been running in circles and even did a file search trying to find where server.ts was hiding but folder SRC does not exist anybody know where zwave js server get installed to?

**Comment by MartinHjelmare** [comment]
Here's that file:
https://github.com/zwave-js/zwave-js-server/blob/master/src/bin/server.ts

If your aim is to install the server as a user and not as a developer and you're having trouble installing from source, I'd recommend you to instead use docker and the zwavejs2mqtt docker image. Once you have docker set up, which is documented at https://docs.docker.com/get-docker/, running that image is easy. Here's the docs for that:
https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/quick-start?id=docker

We can't help you with non project specific questions like how to build a Node.js or TypeScript project. Thanks for your understanding! Good luck!
