### ISSUE TITLE
ZMNHUD Temperature issue

### ISSUE THREAD

**Issue by Balooforever** [zwave-js/zwave-js-server#105]
Hi all,

I use your fantastic ZwaveJS2MQQT with my Home Assistant instance.

i m a French user and I use a Qubino ZMNHUD for my climate.

With this ZMNHUD, I have a Wired Temperature Sensor and it s work with ZwaveJS2MQTT but it s not the good temperature value remote to Home Assistant (Two température value in config panel but  it s not the correct send to HA :()

edit more detail : 
- 24-49-3-Air temperature] Air temperature -> Value send to HA
- 24-49-1-Air temperature] Air temperature -> Correct value needed :)

Can you help me ?

thank a lot :)

**Comment by Balooforever** [comment]
Woups sorry :)

Thank a lot for your help !

**Comment by MartinHjelmare** [comment]
Please open an issue in the Home Assistant core repository.

Also, please create a dump of your Z-Wave network and upload the dump as a text file in that issue after creating it.

The dump tool is available in the configuration panel of the Z-Wave JS integration, reached from the integrations page in the Home Assistant GUI.

The network dump will help us troubleshoot your device.

Thanks!
