### ISSUE TITLE
Where is the zwave-js-server version string hardcoded, or written?

### ISSUE THREAD

**Issue by hassan-xy** [zwave-js/zwave-js-server#1195]
Hi,
I fetch the version number using the line "**logger.info(`zwavejsServer version: ${server_1.serverVersion}`);**"
I tried to search if the version number is hard coded in the files but couldnt find anywhere except in package-lock.json files.
Please update as to from where does the **server_1.serverVersion** fetches the version number i.e 1.31.0 and so on. Is it hard coded in the firmware. Also update if there is a method to hard code it.

Thanks!

**Comment by raman325** [comment]
https://github.com/zwave-js/zwave-js-server/blob/master/package.json#L3
