### ISSUE TITLE
How to fetch sdk version for the zwave controller

### ISSUE THREAD

**Issue by hassan-xy** [zwave-js/zwave-js-server#1198]
Hi guys,
Could you suggest me to fetch the sdk version of the zwave controller into a variable that I can print on the consolelog.

**Comment by raman325** [comment]
Import this: https://github.com/zwave-js/zwave-js-server/blob/master/src/lib/const.ts#L1

**Comment by hassan-xy** [comment]
Hi Raman,
Thanks for the input. But unfortunately this is not what I needed. I need the zwave chip binary version  as shown in the below image.
![image](https://github.com/zwave-js/zwave-js-server/assets/125990448/8338d28d-3784-4700-8b8e-b0f2aaba20a1)

Thanks
