### ISSUE TITLE
OTA for secure application 

### ISSUE THREAD

**Issue by hassan-xy** [zwave-js/zwave-js-server#1273]
Hi team,
I need to know if its possible to perform signed OTA update for the NCP firmware for zwave 700 series ZGM130S037HGN.

Please share the procedure if its applicable.

Thanks

**Comment by raman325** [comment]
Your best bet is to use a platform that integrates with zwave-js. That could be Home Assistant, ioBroker, or whoever else is out there.

This repo is intended to be a lightweight wrapper around zwave-js. It has all the functional elements to allow any client to connect to it over websockets and interact with the Z-Wave network via zwave-js. The commands needed to perform the firmware update are available in the server, but we are primarily targeting embedded use cases so we have no interest in creating or maintaining guides on how to string together commands into an operation..
