### ISSUE TITLE
Updating/Polling/Refreshing/Interviewing Thermostat Fan State Fails

### ISSUE THREAD

**Issue by kaijk** [zwave-js/zwave-js-server#134]
I'm presuming this issue falls under this area as the back-end of ```zwjs2m```.

**Environment:**

- RasPi 3+ Docker
- Controller: Aeotec; Gen5
- zwjs2m version: dev from 20210222
- RadioThermostat CT80 that seems well supported by ```zw-js```:

**Issue:**

- Polling Fan State always returns "0" (zero) which is "Idle/Off"
- Setting Fan State to a non-zero value raises a write error.

**Logs:**
Polling Fan State always returns zero even if the Fan is running:

```zwavejs2mqtt    ZWAVE: Node 3: value updated: 69-0-state 0 => 0```

Setting Fan State to "Running/Low" with ```zwjs2m``` raises write error:
```
zwavejs2mqtt     |   { nodeId: 3, commandClass: 69, endpoint: 0, property: 'state' },
zwavejs2mqtt     |   1,
zwavejs2mqtt     |   [length]: 2
zwavejs2mqtt     | ]
zwavejs2mqtt     | 2021-02-23 01:20:14.485 INFO ZWAVE: Writing 1 to 3-69-0-state
zwavejs2mqtt     | 2021-02-23 01:20:14.492 ERROR ZWAVE: Unable to write 1 on 3-69-0-state
```

**Other Information:**
Note: Executing "Refresh Values" in zwjs2m appears only to request setpoints, and not either the "Thermostat Operating State" (Heating, Idle, Cooling) or the "Thermostat Fan State (Idle, -or various possible other states-).  A full interview will request both states, but only Operating State comes back correctly. Fan State is always zero (Idle/Off).  

May I suggest adding both to "Refresh Values" for Thermostats?

Also, If the thermostat fan is manually (at the device) turned on, it autonomously reports the state and it shows correctly upstream in zwjs2m.

**Comment by marcelveldt** [comment]
Please do not log issues here but at the correct project.
So for issues with the Home Assistant integration, log an issue with Home Assistant core.
In this case you seem to be having an issue with zwavejs2mqtt so please report it there. Thanks!
