### ISSUE TITLE
Enhancement Idea: Emit an event when the log config gets updated

### ISSUE THREAD

**Issue by raman325** [zwave-js/zwave-js-server#231]
I originally tried to PR this into the driver here: https://github.com/zwave-js/node-zwave-js/pull/2672 but Al pointed out that this is a `zwave-js-server` specific problem and that it doesn't belong in the driver, which is fair.

The problem we have is that multiple clients can connect to a single server. In the HomeAssistant frontend, we store the state of the log config, which means if another client updates the log config, the state in the HA frontend that's using a different client will be out of date.

I think it would be great if we could start emitting events when the log config gets updated, with the idea being that the state can be stored in the library and can get updated as needed. Frontend can also react accordingly.

I can start working on this, but wanted to get feedback before attempting it because we will have to figure out how to emit the event and how to catch it (we could use the server since it's an event emitter but we would need to model it in the library so we can add a listener)

**Comment by balloob** [comment]
Do we know of cases where people have two clients ?

**Comment by raman325** [comment]
I don't have any stats but when I asked around in Discord at least a couple of people said that they do or plan to set it up that way. Does it matter though? Shouldn't our design assume multiple clients?
