### ISSUE TITLE
Unknown device

### ISSUE THREAD

**Issue by tweaker** [zwave-js/zwave-js-server#301]
How to add a device that is missing in the database? https://devices.zwave-js.io/

Protection against water leakage, the faucet is added, but the device is unknown.
What do I need to do for that?

https://gidrolock.ru/production/komplekty-gidrolock-winner-z-wave/

**Comment by MartinHjelmare** [comment]
I suggest you join the zwave-js Slack and ask the question there. It's not related to the zwave-js-server.

https://join.slack.com/t/zwave-js/shared_invite/zt-8ns655f6-d407vtI~KjU~1z11jyaQ9Q
