### ISSUE TITLE
Stopping server

### ISSUE THREAD

**Issue by alabamatoy** [zwave-js/zwave-js-server#397]
How to stop the server once its running?

**Comment by kpine** [comment]
Kill the process with `SIGINT` (e.g. CTRL-C) or `SIGTERM` signals.

**Comment by alabamatoy** [comment]
Respectfully, I knew that.  I was expecting there to be a more....graceful way to do it.

**Comment by kpine** [comment]
It is "graceful". The [signal handlers](https://github.com/zwave-js/zwave-js-server/blob/e26b2259468c247e8a902bd82131be9c29779d42/src/bin/server.ts#L127-L147) cleanly shutdown the driver and server.

In my experience most unix services work this way, e.g. [nginx](http://nginx.org/en/docs/control.html).

**Comment by alabamatoy** [comment]
Yes, but there seems no way then to do it through systemd, when it is started via that method.  I looked at trying to capture the process number, but if the server crashes or otherwise gets restarted by systemd, the process number will no longer be correct.

**Comment by kpine** [comment]
You shouldn't need to know anything about PIDs with systemd. It uses SIGTERM by default to stop services, which is what is supported here.

**Comment by kpine** [comment]
FWIW, I'm not an expert in the node.js ecosystem, but it seems like PM2 is the most common way to supervise node applications. If vanilla systemd is not meeting your needs, perhaps consider using PM2 [in conjunction with systemd](https://pm2.keymetrics.io/docs/usage/startup/).
