### ISSUE TITLE
add very basic auth on websocket

### ISSUE THREAD

**Issue by marcelveldt** [zwave-js/zwave-js-server#4]
If users want to secure the websocket they can run it behind NGINX or whatsoever but maybe a very basic authentication on the websocket is not overdone.

Offcourse this can be the responsibility to the application hosting the server (add proxy in front) but as first line of defense we can also incorporate a basic protection with JWT token or whatoever.

An easy solution that just popped my mind is to use the Z-Wave network key (that has to be provided/generated any way) as authentication to protect access to the websocket.

**Comment by marcus-j-davies** [comment]
>If users want to secure the websocket they can run it behind NGINX or whatsoever but maybe a very basic authentication on the websocket is not overdone.

A must in my opinion, especially if the comms are to pass between networks i.e WAN -> LAN

> An easy solution that just popped my mind is to use the Z-Wave network key (that has to be provided/generated any way) as authentication to protect access to the websocket.

My two cents

A common key can be used to encrypt the traffic between client and server, using the crypto package.
the sever and client can require it, in their c'tors

I think there are 2 things here, Authentication and Privacy.

**Comment by marcelveldt** [comment]
Running the server over WAN connections etc. is out of scope and NGINX or other reverse proxy can/should be used for that.
But the internal websocket should also not eb abused by some rogue piece of software that runs in the internal network.

Sure, if some app hosts this server it can (or must) add some IP protection or something but some basic authentication can be added on top of that. For the sakes of complexity of a first release this should be simple but secure.

**Comment by marcus-j-davies** [comment]
Thinking about it, something as simple as passing a key=value in the URL.
`let Socket = new ws('ws://localhost?user=blablabla')`

and checking that value on `wss.on('connection',...`
Dropping the connection on that event, if the value is not correct.

should be able to satisfy most use cases - its certainly simple and should be affective, at least for early development

**Comment by marcelveldt** [comment]
In that case we should this somewhere in the docs that the app hosting/serving the server is responsible for proper authentication and guarding the websocket from being exposed freely.

**Comment by balloob** [comment]
Sounds good. Doing so should be enough to close this issue.

**Comment by OnFreund** [comment]
Sorry for bringing this up from the dead, but if there's no basic authentication I would recommend an option to listen just on localhost. That way it's completely up to a reverse proxy to authenticate/etc..., but the user can prevent the server from being exposed to the network.
