### ISSUE TITLE
dependencies listed as devDependencies in packages.json in z-wave-js-server

### ISSUE THREAD

**Issue by Juul** [zwave-js/zwave-js-server#417]
When running e.g. npm install -g @zwave-js/server and then trying to run zwave-server it becomes obvious that many required dependencies are not installed.

It appears that they are in fact listed in package.json file in @zwave-js/server but as devDependencies which causes them not to be installed automatically using npm install -g <package> at least not using 7.5.2 (node version 12.22.5) which is the version in the official apt repos in the latest stable Debian (Bullseye)

If the correct installation method for zwave-server is different from this npm install command then it is not documented in the @zwave-js/server readme file nor in the advanced installation instructions on the home-assistant.io website.

I originally reported this issue to home-assistant/core as per instructions but Charles Garwood closed the issue and told me to report it here instead.

**Comment by AWSb24** [comment]
I also had to install ws and ts-node manually via npm install -g ws and npm install -g ts-node

**Comment by MartinHjelmare** [comment]
We don't recommend installing the server directly via npm except for development purposes. The recommended way is to use the zwavejs2mqtt docker image or, if you're using Home Assistant, one of the add-ons.

The documention in this project targets developers and not end users.

**Comment by raman325** [comment]
also the server requires node v14 at a minimum. With node v14 from a clean system:

```
in ~/projects/zwave
$ npm install @zwave-js/server

added 191 packages, and audited 192 packages in 25s

33 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
in ~/projects/zwave
$ npm install -g @zwave-js/server

  4 export PATH=/usr/local/bin:$HOME/.toolbox/bin:$PATH¬
added 191 packages, and audited 192 packages in 10s

33 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

With v12:
```
in ~/projects/zwave
$ npm install @zwave-js/server
npm WARN saveError ENOENT: no such file or directory, open '/projects/zwave/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'projects/zwave/package.json'
npm WARN @zwave-js/server@1.14.0 requires a peer of zwave-js@^8.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN zwave No description
npm WARN zwave No repository field.
npm WARN zwave No README data
npm WARN zwave No license field.

+ @zwave-js/server@1.14.0
added 3 packages from 2 contributors and audited 3 packages in 1.692s
found 0 vulnerabilities


in ~/projects/zwave
$ npm install -g @zwave-js/server
.nvm/versions/node/v12.22.8/bin/zwave-server -> .nvm/versions/node/v12.22.8/lib/node_modules/@zwave-js/server/dist/bin/server.js
.nvm/versions/node/v12.22.8/bin/zwave-client -> .nvm/versions/node/v12.22.8/lib/node_modules/@zwave-js/server/dist/bin/client.js
npm WARN @zwave-js/server@1.14.0 requires a peer of zwave-js@^8.9.1 but none is installed. You must install peer dependencies yourself.

+ @zwave-js/server@1.14.0
added 3 packages from 2 contributors in 0.2s
```

You can learn how to install node v14 at the nodejs docs site, but we can't support you any further than that.

**Comment by Juul** [comment]
> We don't recommend installing the server directly via npm except for development purposes. The recommended way is to use the zwavejs2mqtt docker image or, if you're using Home Assistant, one of the add-ons.

You should expect that people might want to use your project in ways that you don't anticipate. It is a very useful project after all :)

It doesn't seem like fixing `npm install` to work as expected would be much work and it would also fix this problem for developers. I don't see why you would want your project to have missing dependencies but perhaps I'm missing something.

**Comment by kpine** [comment]
> It doesn't seem like fixing `npm install` to work as expected would be much work and it would also fix this problem for developers. I don't see why you would want your project to have missing dependencies but perhaps I'm missing something.

There is no missing dependency. zwave-js is defined as a _peer_ dependency so it can be used in other projects, like zwavejs2mqtt. Defining it as a dependency causes version conflicts. You can read about the history of this problem in issue #99.

As Raman has illustrated in his examples, whether the peer dependencies are installed automatically or not depends on which version of npm (not node actually) you are using. Some versions install them automatically, some don't: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependencies. If you don't want to install zwave-js yourself, upgrade to a newer version of node/npm which does it.

**Comment by raman325** [comment]
thanks for the clarification, I made a poor assumption!

**Comment by raman325** [comment]
> You should expect that people might want to use your project in ways that you don't anticipate. It is a very useful project after all :)

People can use the project in ways we don't anticipate. That doesn't mean we should be providing support for those methods. It increases overhead for the developers, reducing the amount of time we can spend on the project itself, and as demonstrated above these aren't project specific issues anyway.
