### ISSUE TITLE
Z-Wave JS Server => Property 'userCallbacks' does not exist on type

### ISSUE THREAD

**Issue by Beerlesklopfer** [zwave-js/zwave-js-server#434]
Reference as wanted:
https://github.com/home-assistant/core/issues/58983

**The Problem**

**#:> /usr/local/bin/ts-node /usr/local/lib/node_modules/@zwave-js/server/src/bin/server.ts /dev/zwave --config /var/lib/homeassistant/zwave.json**

```
TSError: ⨯ Unable to compile TypeScript:
src/lib/controller/message_handler.ts:194:15 - error TS2339: Property 'userCallbacks' does not exist on type '{ strategy: InclusionStrategy.Default; userCallbacks: InclusionUserCallbacks; forceSecurity?: boolean | undefined; } | { strategy: InclusionStrategy.Security_S2; userCallbacks: InclusionUserCallbacks; } | { ...; } | { ...; } | { ...; }'.
  Property 'userCallbacks' does not exist on type '{ strategy: InclusionStrategy.Security_S2; provisioning: PlannedProvisioningEntry; }'.

194       options.userCallbacks = {
                  ~~~~~~~~~~~~~

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:750:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:754:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:941:36)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1243:30)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
```

**#>: cat /var/lib/homeassistant/zwave.json**
```
{
  "logConfig": true,
  "networkKey": "12____________78",
  "storage": {
        "cacheDir": "/var/cache/zwave-js",
        "throttle": "slow"
  }
}

```
**#:> node --version** => v17.0.1

**#:> npm -g list**

```
/usr/local/lib
├── @zwave-js/server@1.10.7
├── npm@8.1.2
├── ts-node@10.4.0
├── tslib@2.3.1
└── typescript@4.4.4

```
**Installation Process:**

```
**sudo npm update
sudo chown -R $USER:$USER /usr/local/lib/node_modules/ 

sudo npm install -g typescript
sudo npm install -g ts-node
sudo npm install -g tslib

sudo npm install -g @zwave-js/server
cd /usr/local/lib/node_modules/@zwave-js/server/
sudo npm install -D zwave-js**
```

**Environment:**
```
Debian Buster 10.10 
Linux homeassistant 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux

```

**Comment by raman325** [comment]
are you attempting to compile zwave-js-server yourself with the latest zwave-js? This won't work because of a change that breaks the current logic. This would get fixed by #433

**Comment by Beerlesklopfer** [comment]
Here is a small diff meanwhile:

```
--- /usr/local/lib/node_modules/@zwave-js/src/lib/controller/message_handler.ts	2021-11-03 14:37:19.330455758 +0100
+++ src/lib/controller/message_handler.ts	2021-11-03 15:02:00.526985333 +0100
@@ -191,7 +191,8 @@
       let validateDSKAndEnterPinPromise:
         | DeferredPromise<string | false>
         | undefined;
-      options.userCallbacks = {
+      if (!("provisioning" in options)) {	  
+	options.userCallbacks = {
         grantSecurityClasses: (
           requested: InclusionGrant
         ): Promise<InclusionGrant | false> => {
@@ -240,6 +241,7 @@
           });
         },
       };
+     }
     }
     return options;
   }
```
```
@zwave-js/server@1.10.8 /usr/local/lib/node_modules/@zwave-js
├── @types/minimist@1.2.2
├── @types/node@16.11.6
├── @types/triple-beam@1.3.2
├── @types/ws@8.2.0
├── @types/yargs@17.0.5
├── @typescript-eslint/eslint-plugin@4.33.0
├── @typescript-eslint/parser@4.33.0
├── alcalzone-shared@4.0.0
├── eslint-config-prettier@8.3.0
├── eslint@7.32.0
├── husky@4.3.8
├── lint-staged@11.2.6
├── minimist@1.2.5
├── prettier@2.4.1
├── ts-node@10.4.0
├── typescript@4.4.4
├── ws@8.2.3
└── zwave-js@8.7.3
```
8.7.3 works with the mock-driver. 

Neither 8.7.3 nor 8.7.2 is working with the Z-Wave Aeon Labs USB-Stick GEN5-Driver here.

```
The `networkKey` option is deprecated in favor of `securityKeys` option. To eliminate this warning, move your networkKey into the securityKeys.S0_Legacy option. Refer to the Z-Wave JS docs for more information
15:31:39.244 DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                      ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                        ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                       ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                      ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                      ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
15:31:39.251 DRIVER   version 8.7.3
15:31:39.253 DRIVER   
15:31:39.255 DRIVER   starting driver...
15:31:39.294 DRIVER   opening serial port /dev/zwave
15:31:39.322 DRIVER   serial port opened
15:31:39.325 SERIAL » [NAK]                                                                   (0x15)
15:31:39.330 DRIVER   loading configuration...
15:31:39.335 CONFIG   version 8.7.3
15:31:40.607 DRIVER   beginning interview...
15:31:40.610 DRIVER   added request handler for AddNodeToNetwork (0x4a)...
                      1 registered
15:31:40.612 DRIVER   added request handler for RemoveNodeFromNetwork (0x4b)...
                      1 registered
15:31:40.615 DRIVER   added request handler for ReplaceFailedNode (0x63)...
                      1 registered
15:31:40.617 CNTRLR   querying controller IDs...
15:31:40.813 SERIAL » 0x01030020dc                                                         (5 bytes)
15:31:40.818 DRIVER » [REQ] [GetControllerId]
15:31:40.830 SERIAL « [ACK]                                                                   (0x06)
15:31:40.837 SERIAL « 0x01080120f4085d240152                                              (10 bytes)
15:31:40.841 SERIAL » [ACK]                                                                   (0x06)
15:31:40.845 DRIVER « [RES] [GetControllerId]
                        payload: 0xf4085d2401
15:31:40.865 CNTRLR   received controller IDs:
                        home ID:     0xf4085d24
                        own node ID: 1
15:31:40.866 CNTRLR   querying API capabilities...
15:31:40.877 SERIAL » 0x01030007fb                                                         (5 bytes)
15:31:40.878 DRIVER » [REQ] [GetSerialApiCapabilities]
15:31:40.883 SERIAL « [ACK]                                                                   (0x06)
15:31:40.889 SERIAL « 0x012b0107010000860001005afe81ff884f1f0000fb9f7da067000080008086000 (45 bytes)
                      000e87300000e0000600000fb
15:31:40.892 SERIAL » [ACK]                                                                   (0x06)
15:31:40.894 DRIVER « [RES] [GetSerialApiCapabilities]
                        payload: 0x010000860001005afe81ff884f1f0000fb9f7da067000080008086000000e8730
                      0000e0000600000
15:31:40.905 CNTRLR   received API capabilities:
                        serial API version:  1.0
                        manufacturer ID:     0x86
                        product type:        0x01
                        product ID:          0x5a
                        supported functions: 
                        · GetSerialApiInitData (0x02)
                        · FUNC_ID_SERIAL_API_APPL_NODE_INFORMATION (0x03)
                        · ApplicationCommand (0x04)
                        · GetControllerCapabilities (0x05)
                        · SetSerialApiTimeouts (0x06)
                        · GetSerialApiCapabilities (0x07)
                        · SoftReset (0x08)
                        · UNKNOWN_FUNC_UNKNOWN_0x09 (0x09)
                        · SetRFReceiveMode (0x10)
                        · UNKNOWN_FUNC_SET_SLEEP_MODE (0x11)
                        · FUNC_ID_ZW_SEND_NODE_INFORMATION (0x12)
                        · SendData (0x13)
                        · SendDataMulticast (0x14)
                        · GetControllerVersion (0x15)
                        · SendDataAbort (0x16)
                        · FUNC_ID_ZW_R_F_POWER_LEVEL_SET (0x17)
                        · UNKNOWN_FUNC_SEND_DATA_META (0x18)
                        · FUNC_ID_ZW_GET_RANDOM (0x1c)
                        · GetControllerId (0x20)
                        · UNKNOWN_FUNC_MEMORY_GET_BYTE (0x21)
                        · UNKNOWN_FUNC_MEMORY_PUT_BYTE (0x22)
                        · UNKNOWN_FUNC_MEMORY_GET_BUFFER (0x23)
                        · UNKNOWN_FUNC_MEMORY_PUT_BUFFER (0x24)
                        · UNKNOWN_FUNC_FlashAutoProgSet (0x27)
                        · GetNVMId (0x29)
                        · ExtNVMReadLongBuffer (0x2a)
                        · ExtNVMWriteLongBuffer (0x2b)
                        · ExtNVMReadLongByte (0x2c)
                        · ExtExtWriteLongByte (0x2d)
                        · GetNodeProtocolInfo (0x41)
                        · HardReset (0x42)
                        · FUNC_ID_ZW_REPLICATION_COMMAND_COMPLETE (0x44)
                        · FUNC_ID_ZW_REPLICATION_SEND_DATA (0x45)
                        · AssignReturnRoute (0x46)
                        · DeleteReturnRoute (0x47)
                        · RequestNodeNeighborUpdate (0x48)
                        · ApplicationUpdateRequest (0x49)
                        · AddNodeToNetwork (0x4a)
                        · RemoveNodeFromNetwork (0x4b)
                        · FUNC_ID_ZW_CREATE_NEW_PRIMARY (0x4c)
                        · FUNC_ID_ZW_CONTROLLER_CHANGE (0x4d)
                        · FUNC_ID_ZW_SET_LEARN_MODE (0x50)
                        · AssignSUCReturnRoute (0x51)
                        · FUNC_ID_ZW_REQUEST_NETWORK_UPDATE (0x53)
                        · SetSUCNodeId (0x54)
                        · DeleteSUCReturnRoute (0x55)
                        · GetSUCNodeId (0x56)
                        · UNKNOWN_FUNC_SEND_SUC_ID (0x57)
                        · FUNC_ID_ZW_EXPLORE_REQUEST_INCLUSION (0x5e)
                        · RequestNodeInfo (0x60)
                        · RemoveFailedNode (0x61)
                        · IsFailedNode (0x62)
                        · ReplaceFailedNode (0x63)
                        · UNKNOWN_FUNC_UNKNOWN_0x66 (0x66)
                        · UNKNOWN_FUNC_UNKNOWN_0x67 (0x67)
                        · GetRoutingInfo (0x80)
                        · UNKNOWN_FUNC_LOCK_ROUTE_RESPONSE (0x90)
                        · UNKNOWN_FUNC_GET_PRIORITY_ROUTE (0x92)
                        · UNKNOWN_FUNC_SET_PRIORITY_ROUTE (0x93)
                        · UNKNOWN_FUNC_UNKNOWN_0x98 (0x98)
                        · UNKNOWN_FUNC_UNKNOWN_0xB4 (0xb4)
                        · UNKNOWN_FUNC_WATCH_DOG_ENABLE (0xb6)
                        · UNKNOWN_FUNC_WATCH_DOG_DISABLE (0xb7)
                        · UNKNOWN_FUNC_WATCH_DOG_KICK (0xb8)
                        · UNKNOWN_FUNC_UNKNOWN_0xB9 (0xb9)
                        · UNKNOWN_FUNC_RF_POWERLEVEL_GET (0xba)
                        · UNKNOWN_FUNC_GET_LIBRARY_TYPE (0xbd)
                        · UNKNOWN_FUNC_SEND_TEST_FRAME (0xbe)
                        · UNKNOWN_FUNC_GET_PROTOCOL_STATUS (0xbf)
                        · UNKNOWN_FUNC_UNKNOWN_0xD2 (0xd2)
                        · UNKNOWN_FUNC_UNKNOWN_0xD3 (0xd3)
                        · UNKNOWN_FUNC_UNKNOWN_0xD4 (0xd4)
                        · undefined (0xee)
                        · UNKNOWN_FUNC_UNKNOWN_0xEF (0xef)
15:31:40.908 CNTRLR   Performing soft reset...
15:31:40.919 SERIAL » 0x01030008f4                                                         (5 bytes)
15:31:40.920 DRIVER » [REQ] [SoftReset]
15:31:40.925 SERIAL « [ACK]                                                                   (0x06)
15:31:40.934 CNTRLR   Waiting for the controller to reconnect...
15:31:42.093 DRIVER   destroying driver instance...
```

**Comment by raman325** [comment]
> Here is a small diff meanwhile:
> 
> ```
> --- /usr/local/lib/node_modules/@zwave-js/src/lib/controller/message_handler.ts	2021-11-03 14:37:19.330455758 +0100
> +++ src/lib/controller/message_handler.ts	2021-11-03 15:02:00.526985333 +0100
> @@ -191,7 +191,8 @@
>        let validateDSKAndEnterPinPromise:
>          | DeferredPromise<string | false>
>          | undefined;
> -      options.userCallbacks = {
> +      if (!("provisioning" in options)) {	  
> +	options.userCallbacks = {
>          grantSecurityClasses: (
>            requested: InclusionGrant
>          ): Promise<InclusionGrant | false> => {
> @@ -240,6 +241,7 @@
>            });
>          },
>        };
> +     }
>      }
>      return options;
>    }
> ```
> 
> ```
> @zwave-js/server@1.10.8 /usr/local/lib/node_modules/@zwave-js
> ├── @types/minimist@1.2.2
> ├── @types/node@16.11.6
> ├── @types/triple-beam@1.3.2
> ├── @types/ws@8.2.0
> ├── @types/yargs@17.0.5
> ├── @typescript-eslint/eslint-plugin@4.33.0
> ├── @typescript-eslint/parser@4.33.0
> ├── alcalzone-shared@4.0.0
> ├── eslint-config-prettier@8.3.0
> ├── eslint@7.32.0
> ├── husky@4.3.8
> ├── lint-staged@11.2.6
> ├── minimist@1.2.5
> ├── prettier@2.4.1
> ├── ts-node@10.4.0
> ├── typescript@4.4.4
> ├── ws@8.2.3
> └── zwave-js@8.7.3
> ```
> 
> 8.7.3 works with the mock-driver.
> 
> Neither 8.7.3 nor 8.7.2 is working with the Z-Wave Aeon Labs USB-Stick GEN5-Driver here.
> 
> ```
> The `networkKey` option is deprecated in favor of `securityKeys` option. To eliminate this warning, move your networkKey into the securityKeys.S0_Legacy option. Refer to the Z-Wave JS docs for more information
> 15:31:39.244 DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
>                       ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
>                         ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
>                        ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
>                       ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
>                       ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
> 15:31:39.251 DRIVER   version 8.7.3
> 15:31:39.253 DRIVER   
> 15:31:39.255 DRIVER   starting driver...
> 15:31:39.294 DRIVER   opening serial port /dev/zwave
> 15:31:39.322 DRIVER   serial port opened
> 15:31:39.325 SERIAL » [NAK]                                                                   (0x15)
> 15:31:39.330 DRIVER   loading configuration...
> 15:31:39.335 CONFIG   version 8.7.3
> 15:31:40.607 DRIVER   beginning interview...
> 15:31:40.610 DRIVER   added request handler for AddNodeToNetwork (0x4a)...
>                       1 registered
> 15:31:40.612 DRIVER   added request handler for RemoveNodeFromNetwork (0x4b)...
>                       1 registered
> 15:31:40.615 DRIVER   added request handler for ReplaceFailedNode (0x63)...
>                       1 registered
> 15:31:40.617 CNTRLR   querying controller IDs...
> 15:31:40.813 SERIAL » 0x01030020dc                                                         (5 bytes)
> 15:31:40.818 DRIVER » [REQ] [GetControllerId]
> 15:31:40.830 SERIAL « [ACK]                                                                   (0x06)
> 15:31:40.837 SERIAL « 0x01080120f4085d240152                                              (10 bytes)
> 15:31:40.841 SERIAL » [ACK]                                                                   (0x06)
> 15:31:40.845 DRIVER « [RES] [GetControllerId]
>                         payload: 0xf4085d2401
> 15:31:40.865 CNTRLR   received controller IDs:
>                         home ID:     0xf4085d24
>                         own node ID: 1
> 15:31:40.866 CNTRLR   querying API capabilities...
> 15:31:40.877 SERIAL » 0x01030007fb                                                         (5 bytes)
> 15:31:40.878 DRIVER » [REQ] [GetSerialApiCapabilities]
> 15:31:40.883 SERIAL « [ACK]                                                                   (0x06)
> 15:31:40.889 SERIAL « 0x012b0107010000860001005afe81ff884f1f0000fb9f7da067000080008086000 (45 bytes)
>                       000e87300000e0000600000fb
> 15:31:40.892 SERIAL » [ACK]                                                                   (0x06)
> 15:31:40.894 DRIVER « [RES] [GetSerialApiCapabilities]
>                         payload: 0x010000860001005afe81ff884f1f0000fb9f7da067000080008086000000e8730
>                       0000e0000600000
> 15:31:40.905 CNTRLR   received API capabilities:
>                         serial API version:  1.0
>                         manufacturer ID:     0x86
>                         product type:        0x01
>                         product ID:          0x5a
>                         supported functions: 
>                         · GetSerialApiInitData (0x02)
>                         · FUNC_ID_SERIAL_API_APPL_NODE_INFORMATION (0x03)
>                         · ApplicationCommand (0x04)
>                         · GetControllerCapabilities (0x05)
>                         · SetSerialApiTimeouts (0x06)
>                         · GetSerialApiCapabilities (0x07)
>                         · SoftReset (0x08)
>                         · UNKNOWN_FUNC_UNKNOWN_0x09 (0x09)
>                         · SetRFReceiveMode (0x10)
>                         · UNKNOWN_FUNC_SET_SLEEP_MODE (0x11)
>                         · FUNC_ID_ZW_SEND_NODE_INFORMATION (0x12)
>                         · SendData (0x13)
>                         · SendDataMulticast (0x14)
>                         · GetControllerVersion (0x15)
>                         · SendDataAbort (0x16)
>                         · FUNC_ID_ZW_R_F_POWER_LEVEL_SET (0x17)
>                         · UNKNOWN_FUNC_SEND_DATA_META (0x18)
>                         · FUNC_ID_ZW_GET_RANDOM (0x1c)
>                         · GetControllerId (0x20)
>                         · UNKNOWN_FUNC_MEMORY_GET_BYTE (0x21)
>                         · UNKNOWN_FUNC_MEMORY_PUT_BYTE (0x22)
>                         · UNKNOWN_FUNC_MEMORY_GET_BUFFER (0x23)
>                         · UNKNOWN_FUNC_MEMORY_PUT_BUFFER (0x24)
>                         · UNKNOWN_FUNC_FlashAutoProgSet (0x27)
>                         · GetNVMId (0x29)
>                         · ExtNVMReadLongBuffer (0x2a)
>                         · ExtNVMWriteLongBuffer (0x2b)
>                         · ExtNVMReadLongByte (0x2c)
>                         · ExtExtWriteLongByte (0x2d)
>                         · GetNodeProtocolInfo (0x41)
>                         · HardReset (0x42)
>                         · FUNC_ID_ZW_REPLICATION_COMMAND_COMPLETE (0x44)
>                         · FUNC_ID_ZW_REPLICATION_SEND_DATA (0x45)
>                         · AssignReturnRoute (0x46)
>                         · DeleteReturnRoute (0x47)
>                         · RequestNodeNeighborUpdate (0x48)
>                         · ApplicationUpdateRequest (0x49)
>                         · AddNodeToNetwork (0x4a)
>                         · RemoveNodeFromNetwork (0x4b)
>                         · FUNC_ID_ZW_CREATE_NEW_PRIMARY (0x4c)
>                         · FUNC_ID_ZW_CONTROLLER_CHANGE (0x4d)
>                         · FUNC_ID_ZW_SET_LEARN_MODE (0x50)
>                         · AssignSUCReturnRoute (0x51)
>                         · FUNC_ID_ZW_REQUEST_NETWORK_UPDATE (0x53)
>                         · SetSUCNodeId (0x54)
>                         · DeleteSUCReturnRoute (0x55)
>                         · GetSUCNodeId (0x56)
>                         · UNKNOWN_FUNC_SEND_SUC_ID (0x57)
>                         · FUNC_ID_ZW_EXPLORE_REQUEST_INCLUSION (0x5e)
>                         · RequestNodeInfo (0x60)
>                         · RemoveFailedNode (0x61)
>                         · IsFailedNode (0x62)
>                         · ReplaceFailedNode (0x63)
>                         · UNKNOWN_FUNC_UNKNOWN_0x66 (0x66)
>                         · UNKNOWN_FUNC_UNKNOWN_0x67 (0x67)
>                         · GetRoutingInfo (0x80)
>                         · UNKNOWN_FUNC_LOCK_ROUTE_RESPONSE (0x90)
>                         · UNKNOWN_FUNC_GET_PRIORITY_ROUTE (0x92)
>                         · UNKNOWN_FUNC_SET_PRIORITY_ROUTE (0x93)
>                         · UNKNOWN_FUNC_UNKNOWN_0x98 (0x98)
>                         · UNKNOWN_FUNC_UNKNOWN_0xB4 (0xb4)
>                         · UNKNOWN_FUNC_WATCH_DOG_ENABLE (0xb6)
>                         · UNKNOWN_FUNC_WATCH_DOG_DISABLE (0xb7)
>                         · UNKNOWN_FUNC_WATCH_DOG_KICK (0xb8)
>                         · UNKNOWN_FUNC_UNKNOWN_0xB9 (0xb9)
>                         · UNKNOWN_FUNC_RF_POWERLEVEL_GET (0xba)
>                         · UNKNOWN_FUNC_GET_LIBRARY_TYPE (0xbd)
>                         · UNKNOWN_FUNC_SEND_TEST_FRAME (0xbe)
>                         · UNKNOWN_FUNC_GET_PROTOCOL_STATUS (0xbf)
>                         · UNKNOWN_FUNC_UNKNOWN_0xD2 (0xd2)
>                         · UNKNOWN_FUNC_UNKNOWN_0xD3 (0xd3)
>                         · UNKNOWN_FUNC_UNKNOWN_0xD4 (0xd4)
>                         · undefined (0xee)
>                         · UNKNOWN_FUNC_UNKNOWN_0xEF (0xef)
> 15:31:40.908 CNTRLR   Performing soft reset...
> 15:31:40.919 SERIAL » 0x01030008f4                                                         (5 bytes)
> 15:31:40.920 DRIVER » [REQ] [SoftReset]
> 15:31:40.925 SERIAL « [ACK]                                                                   (0x06)
> 15:31:40.934 CNTRLR   Waiting for the controller to reconnect...
> 15:31:42.093 DRIVER   destroying driver instance...
> ```

They are not working even with the changes in your diff? (which are consequently also in the PR I linked to 🙂 )

**Comment by Beerlesklopfer** [comment]
raman325's version  is working.
Driverversion: 8.5.0
Serverversion: 1.10.7

The patch above does it only with the mock-driver...

**Comment by kpine** [comment]
@raman325 I think I am seeing the same problem as shown in the driver debug logs above. The driver gets destroyed for some reason. This was the issue I was debugging with Al in Discord.

**Comment by kpine** [comment]
> Neither 8.7.3 nor 8.7.2 is working with the Z-Wave Aeon Labs USB-Stick GEN5-Driver here.

This particular problem is an [issue](https://github.com/zwave-js/node-zwave-js/issues/3663) with node-zwave-js and the server application. It's going to be fixed in the driver (I imagine in a 8.7.5 release). For now, you can workaround it by disabling the [soft-reset](https://zwave-js.github.io/node-zwave-js/#/api/driver?id=softreset) functionality.

**Comment by Beerlesklopfer** [comment]
Maybe disabling the reset functionality could be a an configurable option. Either in a config file or via environment.

Beste Grüße aus Lemgo

Jörg Bernau

**Comment by kpine** [comment]
> Maybe disabling the reset functionality could be a an configurable option. Either in a config file or via environment.

Both of those are already options, they are explained in the docs.
