### ISSUE TITLE
add support for node commands

### ISSUE THREAD

**Issue by marcelveldt** [zwave-js/zwave-js-server#5]
Add support of sending commands to Z-wave nodes, most important the setValue command

**must have commands:**

- [x] setValue

**nice to have commands:**

- [ ] firmware update
- [ ] refreshInfo
- [ ] getDefinedValueIDs
- [ ] getValueMetadata

**Comment by Michsior14** [comment]
@balloob I would be happy to help you with other commands. I guess `snake_case` is way to go when defining the new one?

**Comment by balloob** [comment]
Yes. I accidentally went that way for `start_listening`. Just going with the flow :)
