### ISSUE TITLE
S2 Inclusion: abort callback can trigger an unhandled promise rejection

### ISSUE THREAD

**Issue by marcus-j-davies** [zwave-js/zwave-js-server#501]
### Describe the bug

Testing the **abort** callback in the .NET wrapper.
I decided to allow the **abort** method to trigger - (I delayed returning the **InclusionGrant**)

In the server, the **abort**  callback also includes rejecting the **validateDSKAndEnterPin** and **grantSecurityClasses** promises.

This, from my investigation, caused the **driver.start()** promise to fail with an unhandled promise rejection.

The server does this:
```javascript
 abort: (): void => {
            grantSecurityClassesPromise?.reject("aborted");
            validateDSKAndEnterPinPromise?.reject("aborted");
            client.sendEvent({
              source: "controller",
              event: "inclusion aborted",
            });
          }
```

The **driver.start()** promise gets.
```log
This error originated either by throwing inside of an async function without a catch block,
or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
aborted

```

### Which branches or versions?

8.11.0

### Attach Driver Logfile

[zwave-js.log_2022-01-16.log](https://github.com/zwave-js/node-zwave-js/files/7877085/zwave-js.log_2022-01-16.log)

**Comment by marcus-j-davies** [comment]
@raman325,

I don't think we need to reject these promises  - or if there is a need, to  catch them.
the abort callback is causing an unhandled rejection - see my first comment.

**Comment by raman325** [comment]
> Ideally the server wouldn't reject the promise itself.

sorry, probably just should have looked here before commenting on the other one, but why not?
