### ISSUE TITLE
zwavejs2mqtt coexistence 

### ISSUE THREAD

**Issue by marcelveldt** [zwave-js/zwave-js-server#6]
@robertsLando Issued a ticket here as some sort of reminder ;-)

Atm zwavejs2mqtt directly loads the zwave-js lib. Now that we're working on the zwave server websocket api we want to look for ways to give users flexibility. Any app can off-course utilize the api if it's running in the network but zwave2mqtt currently is talking talking to the zwavejs lib.

A few possible options:

- zw2mqtt also utilizes the websocket api
- zw2mqtt serves the server by itself

**Comment by balloob** [comment]
This is already taken care of. We expose a method to add our API to an existing Express app. Just pass in the express app and the Z-Wave JS driver:

https://github.com/zwave-js/zwave-js-server/blob/a86f20530df12d2f5e7aaa4001c7292f12f3836e/lib/express.ts#L108

Z-Wave JS 2 MQTT uses Express and has a driver object, so this should be fairly straightforward.

**Comment by robertsLando** [comment]
Yep in my idea I would just require your server into my gateway like `startServer(zwaveDriver)`
