### ISSUE TITLE
docs: I assume I need to open port 3000 on the dockerhub zwavejs2mqtt:dev container

### ISSUE THREAD

**Issue by scyto** [zwave-js/zwave-js-server#66]
Looks like this is now built into zwavejs2mqtt:dev  i assume i need to add - 3000:3000 to the ports section of my docker compose?

If so i can do a PR for that compose file in the zwavejs2mqtt branches if needed?

**Comment by robertsLando** [comment]
@scyto The port can be configured in zwavejs2mqtt but yes feel free to submit a pr

**Comment by scyto** [comment]
sure, i was more getting at that if that port is not exposed and the docker is using bridge networking then the 3000 port will be inaccessible to anything outside docker... like the HA integration?

**Comment by robertsLando** [comment]
Fork and PR :)

**Comment by marcelveldt** [comment]
@scyto if HA is running on the same host, better not to open the port and connect to the server using internal docker network.
