### ISSUE TITLE
Question about zwave-js-server license

### ISSUE THREAD

**Issue by brennanwilkes** [zwave-js/zwave-js-server#718]
Since the core [node-zwave-js](https://github.com/zwave-js/node-zwave-js) library is under the MIT license, is this package also intended to be under MIT, or is this package restricted for commercial use?

Thanks!

**Comment by kpine** [comment]
The license is Apache 2.0. Ideally there should be a LICENSE file added to the project.

https://github.com/zwave-js/zwave-js-server/blob/1973f99dc0c243389dc311152b5f55da2d2573d1/package.json#L30
