### ISSUE TITLE
API call format [question]

### ISSUE THREAD

**Issue by chrish987** [zwave-js/zwave-js-server#73]
I am trying to call a node.get_value function with the websocket, but despite trying many formats cannot get a success result.

Note sure if I am miles off here, but can't really see how to specify the node_id.

I am sending:
{
    "messageId": "test",
    "command": "node.get_value",
    "valueId": {
        "commandClass": 49,
        "endpoint?": 0,
        "property": "humidity",
        "propertyKey?": "xxx"
    }
}

and the response is:
{"type":"result","success":false,"messageId":"test","errorCode":"node_not_found"}

Any pointers gratefully received.

**Comment by balloob** [comment]
You didn't specify a node

**Comment by chrish987** [comment]
are you able to give an example input? I can't see how to specify the node and have not been able to find any examples.
Thanks
