### ISSUE TITLE
Update Failed: Invalid server version: Z-Wave JS Server version is incompatible: 1.21.0 a version is required that supports at least api schema 22

### ISSUE THREAD

**Issue by rsschaap** [zwave-js/zwave-js-server#738]
Update on HAOS failed ends with: 
Invalid server version: Z-Wave JS Server version is incompatible: 1.21.0 a version is required that supports at least api schema 22
Control panel only shows error message.

**Comment by MartinHjelmare** [comment]
This is the wrong place to open an issue. If you're running Home Assistant, please report any issues in the Home Assistant core repository.

Make sure to include all relevant information, like how you are running the zwave-js-server.
