### ISSUE TITLE
Support configuring the user agent of the driver

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js-server#740]
The driver recently added support for configuring the user agent that is used to make requests to our web services: https://github.com/zwave-js/node-zwave-js/pull/5031.
The server should register itself there, either using the https://zwave-js.github.io/node-zwave-js/#/api/driver?id=updateuseragent method (if it is NOT creating the driver instance itself) or using the `userAgent` driver option: https://zwave-js.github.io/node-zwave-js/#/api/driver?id=zwaveoptions 
Connected applications like HA should also register themselves.

**Comment by balloob** [comment]
Ideally I think that the server should always add it's identification to each request, and if the client is requesting something, we add their user agent to it too.

**Comment by raman325** [comment]
The way this is set up, multiple client support wouldn't work very well unless we updated the user agent every time we send a request. Is that what you are suggesting?

**Comment by AlCalzone** [comment]
Do you have a better idea? I guess I could add a userAgent option to each method that uses one and use it to extend the configured one for this call.
But how realistic is a multi-app usage right now anyways?

**Comment by raman325** [comment]
> Do you have a better idea? I guess I could add a userAgent option to each method that uses one and use it to extend the configured one for this call.
I think this is the only reasonable way for multi client to work if we want to include a client user agent. One thing you could do is have a base user agent set in the options and any user agents get provided in the call just get tacked on?
> But how realistic is a multi-app usage right now anyways?
Hard to quantify - it's clear it happens, there have been issues opened related to it, but I doubt the usage is high. With that being said, the server supports it so 🤷🏾
