### ISSUE TITLE
no way to reset zwave radio

### ISSUE THREAD

**Issue by psittaciform** [zwave-js/zwave-js-server#757]
I attempted to send command "driver.hard_reset" and got an unknown_command error code back.

```{"type":"result","success":false,"messageId":"66d9bed4-4c99-4046-8261-e1c2a00162cf","errorCode":"unknown_command","args":{"command":"driver.hard_reset"}}```

Let me know if there is any more information I can provide.

**Comment by balloob** [comment]
That's not a supported command. For a list of supported commands see https://github.com/zwave-js/zwave-js-server#driver-level-commands

**Comment by psittaciform** [comment]
@balloob are you open to a PR that adds it?  it would be helpful for the integration I'm working on, but I don't want to waste my time if it is going to be rejected.
