### ISSUE TITLE
[Bug]: Bad ws-server "serverHost" leads to crash that prevents fixing the problem

### ISSUE THREAD

**Issue by LordMike** [zwave-js/zwave-js-server#782]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.1.0

### ZwaveJS version

10.3.0

### Describe the bug

For reasons, I had a hostname written in my "Home Assistant" WS Server "Server Host" setting. This value was wrong and does not exist anymore, which leads to this issue:

```
2022-10-16 19:27:01.927 INFO Z-WAVE: Node 85: value added 85-135-0-80-3 => 0
2022-10-16 19:27:01.928 INFO Z-WAVE: Node 85: value added 85-135-0-80-4 => 0
2022-10-16 19:27:01.929 INFO Z-WAVE: Node 85: value added 85-135-0-80-5 => 0
2022-10-16 19:27:01.931 INFO Z-WAVE: Node 85: value added 85-135-0-value => undefined
2022-10-16 19:27:01.937 INFO Z-WAVE: Node 85 ready: Aeotec Ltd. - ZWA019 (Water Sensor 7 Pro)
2022-10-16T17:27:01.938Z CNTRLR   [Node 085] The node is ready to be used
2022-10-16 19:27:01.941 INFO Z-WAVE: Node 92 is alive
2022-10-16T17:27:01.942Z CNTRLR   [Node 092] The node is alive.
2022-10-16 19:27:01.959 INFO Z-WAVE: Node 92 ready: AEON Labs - ZW090 (Z‐Stick Gen5 USB Controller)
2022-10-16T17:27:01.960Z CNTRLR   [Node 092] The node is ready to be used
Error: getaddrinfo ENOTFOUND core-zwave-js
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
[19:27:03] WARNING: Z-Wave JS UI crashed, halting add-on
[19:27:03] INFO: Z-Wave JS UI stoped, restarting...
s6-rc: info: service legacy-services: stopping
[19:27:03] INFO: Z-Wave JS UI stoped, restarting...
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

When the DNS lookup comes back, the UI crashes. So I have about ~30 seconds to fix it, which I tried, but didn't succeed.. Maybe the save-settings failed or zwave-js-ui is locked while it's starting up. I finally fixed it by setting `serverHost` in the config to null.

### To Reproduce

1. Enable Home Assistant integration
2. Configure a server hostname that does not exist
3. Restart zwave-js-ui
4. On startup, it should lookup the name and fail, after which it should crash with the above log
5. Bonus: See if it's possible to open settings on start, and quickly change the server hostname to nothing and save to recover.

### Expected behavior

Some visual feedback that the server hostname is invalid.

**Comment by LordMike** [comment]
> For your immediate problem, have you tried editing the setting in the settings file to remove that key and value? Is anything else logging from zwave-js-ui when it is crashing?
> 

Thats what I did of course. Nothing else blocked me from running the ui.

**Comment by raman325** [comment]
> I have no way to catch that error, as you see I already catch start error that is where the listen is called. there should be a 'error' listener on server in order to fix that. It's something for @raman325

We attempt to catch the error here: https://github.com/zwave-js/zwave-js-server/blob/master/src/lib/server.ts#L440-L441

And emit an error here: https://github.com/zwave-js/zwave-js-server/blob/master/src/lib/server.ts#L462-L465

But in my local testing I can't get that to catch. Are we trying to catch on the wrong thing? What seems to be triggering this is during the listen call but http.Server does not emit an error, nor does the listen method itself raise an exception.

**Comment by blhoward2** [comment]
Just a shot in the dark, but a quick google suggests that only binds to errors emitted, not errors thrown during startup. Try adding a .catch() to the this.server.listen declaration.

**Comment by robertsLando** [comment]
Oh if you are using emit "error" on server instance I have to listen on that, all error events must have a listener in nodejs otherwise them are treated as exceptions. Didn't know you was emitting that, will fix this on my side

**Comment by raman325** [comment]
I am not sure that it's working, so let me know if you are able to catch the error
