### ISSUE TITLE
Server no longer returns "notification" events

### ISSUE THREAD

**Issue by raman325** [zwave-js/zwave-js-server#83]
On b2, I could see "notification" events. I see that for b3 there were changes made to event handling logic, whatever was done has resulted in "notification" events not getting returned anymore. I can see the difference when I switch back and forth:

b2:
- I see notification events
- I don't see value update events

b3:
- I see value update events
- I don't see notification events

**Comment by marcelveldt** [comment]
Nothing changed in b3 for node notifications, they're still forwarded as-is.
Was your network fully started when you ran the tests ?
Maybe connect with a websocket client to the server to see what messages are sent ?

**Comment by raman325** [comment]
I think this is an issue with my device and not the server. Apologies for the misdirect
