### ISSUE TITLE
Set Configuration for Node via WS API, or even MQTT if not yet possible

### ISSUE THREAD

**Issue by marc-gist** [zwave-js/zwave-js-server#85]
Thank you for a wonderful program.
I have used it with the new HA integration, but before I can replace the legacy system, I need to know how to send Parameter Value changes via automations?  One can do this vi HA in the original system via 'zwave.set_config_parameter'

How does ZwaveJS do it?  I can do via its UI, but I need automations to do it.  I also use Node-Red so hoped I could do it from there sending to the Websocket? (as I have mqtt disable so that I can just use via HA's new integration)

Thanks!
Marc

**Comment by marcelveldt** [comment]
Support for service calls will be added in a later release of Home Assistant. In that case you can use zwave_js.set_config_param again like you're used to now with OZW.

BTW: Please report issues for the Home Assistant integration to the Home Assistant issue tracker. Thanks!

**Comment by marc-gist** [comment]
> Support for service calls will be added in a later release of Home Assistant. In that case you can use zwave_js.set_config_param again like you're used to now with OZW.
> 
> BTW: Please report issues for the Home Assistant integration to the Home Assistant issue tracker. Thanks!

I don't care about HomeAssistant service calls.  I can make them directly to the web socket if you can point me in the right direction/documentation please?

**Comment by marcelveldt** [comment]
Issue a command in the following format:

{ 
  "messageId" : 1,
  "command": "setValue",
  "valueID: { a full valueID object},
  "value": the value it should be
}

To get the values you can send, issue a "start_listening" command and it will dump all valueIds as part of each node

**Comment by marcelveldt** [comment]
But you could also use mqtt of course
