### ISSUE TITLE
No Entity Created when Z-Wave Node Added (Older Device)

### ISSUE THREAD

**Issue by davidjmeier** [zwave-js/zwave-js-server#88]
Testing `zwave-js` I grabbed an old Intermatic dimmer I had laying around and installed a clean version of the latest RaspberryPi 64-bit installation of HomeAssistant.

Attached is the Z-Wave dumpfile.

The device in question shows up as:
```
HA03
by Intermatic
Firmware: 1.0
Z-Wave Info
Home ID: 3261845704
Node ID: 5
Node Status: Alive
Node Ready: Yes
```

The issue is that no Entity is created when adding this device on a completely clean installation.  I validated "_Enable newly added entities_" is turned on in the system options for the integration.  The Z-Wave interface shows up as the following:
```
HUSBZB-1
by Sigma Designs (Former Zensys)
Z-Wave Info
Home ID: 3261845704
Node ID: 1
Node Status: Alive
Node Ready: Yes
```

The `core-zwave-js` shows the following:
```
Driver Version: 6.1.1
Server Version: 1.0.0-beta.4
Home ID: 3261845704
Nodes ready: 2 / 2
```

Thank you!

File attachment: [zwave_js_dump.jsonl.txt](https://github.com/zwave-js/zwave-js-server/files/5929392/zwave_js_dump.jsonl.txt)

**Comment by marcelveldt** [comment]
Can you please issue reports about the Home Assistant integration on the Home Assistant issue tracker? Thanks!
Can you verify that the device is on the supported devices list ? https://devices.zwave-js.io/

**Comment by davidjmeier** [comment]
I [originally posted](https://community.home-assistant.io/t/no-zwave-entity-created/276938) regarding the issue in the Home Assistant forums and was directed to create an issue here.  Apologies if this is the wrong place to drop this issue @marcelveldt.  The device is not on the list, but given it was an older and popular device that works in other Z-Wave controllers I wanted to report it.

Was just going to close this but looks like @balloob just did that for me.  Thanks all!
