### ISSUE TITLE
server.ts crashes immediately

### ISSUE THREAD

**Issue by zeddski** [zwave-js/zwave-js-server#89]
Clean install of npm and ts-node.
Downloaded zwave-js-server and run 'ts-node src/bin/server.ts --mock'.
Result:
```
ts-node src/bin/server.ts --mock

/usr/local/lib/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/bin/server.ts:3:25 - error TS2307: Cannot find module 'path' or its corresponding type declarations.

3 import { resolve } from "path";
                          ~~~~~~
src/bin/server.ts:4:24 - error TS2307: Cannot find module 'zwave-js' or its corresponding type declarations.

4 import { Driver } from "zwave-js";
                         ~~~~~~~~~~
src/bin/server.ts:31:26 - error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add `node` to the types field in your tsconfig.

31     configPath = resolve(process.cwd(), configPath);
                            ~~~~~~~
src/bin/server.ts:38:17 - error TS2591: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add `node` to the types field in your tsconfig.

38       options = require(configPath);
                   ~~~~~~~
src/bin/server.ts:42:30 - error TS2591: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add `node` to the types field in your tsconfig.

42         options.networkKey = Buffer.from(options.networkKey, "hex");
                                ~~~~~~
src/bin/server.ts:47:30 - error TS2591: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add `node` to the types field in your tsconfig.

47         options.networkKey = Buffer.from(options.networkKey, "hex");
                                ~~~~~~
src/bin/server.ts:86:7 - error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add `node` to the types field in your tsconfig.

86       process.exit();
         ~~~~~~~
src/bin/server.ts:96:5 - error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add `node` to the types field in your tsconfig.

96     process.exit();
       ~~~~~~~
src/bin/server.ts:99:3 - error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add `node` to the types field in your tsconfig.

99   process.on("SIGINT", handleShutdown);
     ~~~~~~~
src/bin/server.ts:100:3 - error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add `node` to the types field in your tsconfig.

100   process.on("SIGTERM", handleShutdown);
      ~~~~~~~

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

```

What I've tried:
* Run as regular user and root - same result
* used real Z-wave device (/dev/ttyAMA0) in steadd of mock - same result
* Tried a docker container (kpine/zwave-js-server:latest). Crashed without a descriptive error - didn't investigate yet.

Environment:
* RPI 4
* Running raspbian lite 
* Zwave.Me RaZberry 2 (although, not relevant since --mock crashed too)
* tcp/3000 is available

**Comment by balloob** [comment]
Your NodeJS is probably too old.

**Comment by zeddski** [comment]
New system, freshly installed from Debian sources...
But, I've worked around it by installing a different container (zwavejs2mqtt) which provides the Websocket I was looking for.
I'll close this issue, as I won't be updating it.

**Comment by colby82** [comment]
I'm also getting this same error. My version of Node is v15.8.0. Any ideas to try to get it running?

Pi3 - running DietPi_RPi-ARMv8-Buster

Downloaded the zip > copied the folder to the pi via SSH > ran the command to start the server and I get the same errors as @zeddski. You can also at the bottom that it's on node v15.8.0.

`root@DietPi:~/zwave-js-server-master/zwave-js-server-master# ts-node src/bin/server.ts /dev/zwave

/usr/local/lib/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/bin/server.ts:3:25 - error TS2307: Cannot find module 'path' or its corresponding type declarations.

3 import { resolve } from "path";
                          ~~~~~~
src/bin/server.ts:4:24 - error TS2307: Cannot find module 'zwave-js' or its corresponding type declarations.

4 import { Driver } from "zwave-js";
                         ~~~~~~~~~~
src/bin/server.ts:31:26 - error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add `node` to the types field in your tsconfig.

31     configPath = resolve(process.cwd(), configPath);
                            ~~~~~~~
src/bin/server.ts:38:17 - error TS2591: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add `node` to the types field in your tsconfig.

38       options = require(configPath);
                   ~~~~~~~
src/bin/server.ts:42:30 - error TS2591: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add `node` to the types field in your tsconfig.

42         options.networkKey = Buffer.from(options.networkKey, "hex");
                                ~~~~~~
src/bin/server.ts:47:30 - error TS2591: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add `node` to the types field in your tsconfig.

47         options.networkKey = Buffer.from(options.networkKey, "hex");
                                ~~~~~~
src/bin/server.ts:86:7 - error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add `node` to the types field in your tsconfig.

86       process.exit();
         ~~~~~~~
src/bin/server.ts:96:5 - error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add `node` to the types field in your tsconfig.

96     process.exit();
       ~~~~~~~
src/bin/server.ts:99:3 - error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add `node` to the types field in your tsconfig.

99   process.on("SIGINT", handleShutdown);
     ~~~~~~~
src/bin/server.ts:100:3 - error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add `node` to the types field in your tsconfig.

100   process.on("SIGTERM", handleShutdown);
      ~~~~~~~

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
root@DietPi:~/zwave-js-server-master/zwave-js-server-master# node --version
v15.8.0`
