### ISSUE TITLE
TS node Not found

### ISSUE THREAD

**Issue by trentjw** [zwave-js/zwave-js-server#92]
tried installing this finally got it cloned but tried running ts-node src/bin/server.ts /dev/tty0 got error ts node not found

**Comment by trentjw** [comment]
also tried ts-node src/bin/server.ts /dev/ttyACM0

**Comment by trentjw** [comment]
perhaps a step by step install instruction from a bare bones system would help

**Comment by robertsLando** [comment]
@trentjw In order to use `ts-node` you need to have it installed globally or use `npx ts-node`
