### ISSUE TITLE
When starting server up its freezing.

### ISSUE THREAD

**Issue by XVBinh** [zwave-js/zwave-js-server#948]
When I have run the command ``ts-node /root/node_modules/@zwave-js/server/src/bin/server.ts --mock-driver`` the terminal just freezes with ``Starting server on 0.0.0.0:3000
ZwaveJS server listening on 0.0.0.0:3000
DNS Service Discovery enabled``
How can I fix that issue?

**Comment by raman325** [comment]
have you tried connecting a client to the server?

**Comment by XVBinh** [comment]
How do I do that? 
![image](https://github.com/zwave-js/zwave-js-server/assets/36200756/eabeb8a1-2fa3-4df8-8808-e01b9713d9ea)
Now its just stuck at this

**Comment by raman325** [comment]
what are you expecting to happen? It's a server, it's waiting for a connection from a client which can issue it commands and retrieve information

**Comment by XVBinh** [comment]
Yeah but how do I now connect with a client? I can't now put some commands in or when i'm trying to access it from my pc with http://192.168.1.155:3000/ or  ws://0.0.0.0:3000/. Nothing pops up. How do I do that?

**Comment by XVBinh** [comment]
And I thought that you put in the ip adress and then get some ui to configure the server

**Comment by raman325** [comment]
What are you trying to accomplish? you would need to use a client that can:
a) Uses websockets to communicate with the server
b) Uses the server's API to implement back and forth communication

You can't just enter the url into the browser to have things work. And the server doesn't come with a Ui, if you want a UI you need to use zwave-js-ui.

I googled your username and I see that you have been posting in the Home Assistant community about adding zwave to your HA instance. Please read the integration documentation and follow the instructions there, the path you are taking is not the right one, and this isn't the right support forum for what you are trying to accomplish
