### ISSUE TITLE
Inconsistency in zwave-js dependencies

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js-server#99]
I'm not sure if this is the fault of the server module or zwavejs2mqtt, but here it goes...
We have two copies of the zwave-js dependencies in the Docker container.

https://github.com/zwave-js/node-zwave-js/issues/1615#issuecomment-775209809
```
/usr/src/app # find . | grep tz69
./node_modules/@zwave-js/server/node_modules/@zwave-js/config/config/devices/0x0118/tz69.json
./node_modules/@zwave-js/config/config/devices/0x0118/tz69.json
```

This is going to cause some headaches. /cc @robertsLando @balloob @marcelveldt

**Comment by balloob** [comment]
This happens because the version dependencies are conflicting. 

Step 1 is that we should set up more wide version ranges. That way when npm/yarn resolved 

A more appropriate fix would be to move `zwave-js` to peerDependencies so it's at a bring-your-own dependency. This will be a breaking change for all Docker containers as they now have to install their own extra dep. 

The downside of this approach is that it would make it trickier to use the server as a CLI, as you now need to install zwave-js too.

**Comment by AlCalzone** [comment]
`npm` might be weird here, but I wouldn't consider ^6.1.1 and ^6.1.3 as conflicting. 6.1.3 should satisfy both ranges. 

Or maybe the lockfiles are conflicting?
zjs2m:
```
    "@zwave-js/server": {
      "version": "1.0.0-beta.4",
      "resolved": "https://registry.npmjs.org/@zwave-js/server/-/server-1.0.0-beta.4.tgz",
      "integrity": "sha512-sDk6AnMiH1WZIJaeRB/QNqI+pHAmcycohnn2qks8ZorvOL0poyDhtAVl7GJhb/vfXSeFyTxa7a7ssPE9Bn6h5g==",
      "requires": {
        "minimist": "^1.2.5",
        "ws": "^7.4.2",
        "zwave-js": "^6.1.1"
      },
```

server:
```
    "zwave-js": {
      "version": "6.1.3",
      "resolved": "https://registry.npmjs.org/zwave-js/-/zwave-js-6.1.3.tgz",
      "integrity": "sha512-QQ7RtR7lek9JMCnFDz8zqsM1uskdtSA1TL922r7tYb0l/VXO3Cqtehw/+r65lWKotbbHf31G5ThgKry5z+0zMw==",
```

**Comment by robertsLando** [comment]
I think the problem is lock files

**Comment by balloob** [comment]
Lock files of dependencies should be ignored

**Comment by balloob** [comment]
We can run `npm dedupe` in the Dockerfile to prevent this

https://docs.npmjs.com/cli/v6/commands/npm-dedupe

**Comment by AlCalzone** [comment]
Depends on how the dependencies are installed in the container. If using `npm ci` or `yarn --frozen-lockfile`, the lockfiles are respected.

**Comment by AlCalzone** [comment]
We figured out why: Your published npm package includes a `npm-shrinkwrap.json`, which forces `npm` to install all devDependencies, even when you just want to install the production package.

**Comment by AlCalzone** [comment]
From https://docs.npmjs.com/cli/v6/configuring-npm/shrinkwrap-json:
> It's **strongly discouraged** for library authors to publish this file, since that would prevent end users from having control over transitive dependency updates.

**Comment by AlCalzone** [comment]
duplicate of #113
